## WEEK-1
### Constants , Sequences and Random Values

In [1]:
import tensorflow as tf
import numpy as np

In [9]:
a = tf.constant(0.0, shape=[2,3] )

In [14]:
b = tf.constant(np.arange(6), shape=[2,3], dtype=tf.float32)

In [21]:
c = tf.lin_space(start=5.0, stop=10.0, num=50, name="lin")

In [23]:
d = tf.range(start=10, limit=100, delta=2, name="arange")

In [25]:
with tf.Session() as sess:
    print("#################")
    print(sess.run(a))
    print("#################")
    print(sess.run(b))
    print("#################")
    print(sess.run(c))
    print("#################")
    print(sess.run(d))

#################
[[0. 0. 0.]
 [0. 0. 0.]]
#################
[[0. 1. 2.]
 [3. 4. 5.]]
#################
[ 5.         5.102041   5.2040815  5.3061223  5.408163   5.5102043
  5.612245   5.714286   5.8163266  5.9183674  6.020408   6.122449
  6.2244897  6.3265305  6.4285717  6.5306125  6.632653   6.734694
  6.836735   6.9387755  7.0408163  7.1428576  7.244898   7.346939
  7.4489794  7.5510206  7.6530614  7.755102   7.857143   7.9591837
  8.061225   8.163265   8.265306   8.367347   8.469388   8.571428
  8.67347    8.775511   8.877551   8.979592   9.081633   9.183674
  9.285715   9.387755   9.489796   9.591837   9.693878   9.795918
  9.897959  10.       ]
#################
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]


## RANDOM TENSORS

In [26]:
r = tf.random_normal( shape=[3,3], mean=0, stddev=2)

In [31]:
r_truncated = tf.truncated_normal(shape=[3,3], mean=0, stddev=2)

In [35]:
uni = tf.random_uniform(shape=[3,3], minval=0, maxval=2)

In [40]:
x = tf.constant(np.arange(6), shape=[3,2] )
x_shuffled = tf.random_shuffle(value=x)

In [42]:
with tf.Session() as sess:
    print("#################")
    print(sess.run(r))
    print("#################")
    print(sess.run(r_truncated))
    print("#################")
    print(sess.run(uni))
    print("#################")
    print(sess.run(x))
    print(sess.run(x_shuffled))

#################
[[ 2.8409982   0.21681468 -1.1828083 ]
 [-1.2804017   0.8511904   0.6403635 ]
 [-0.5709736   3.6245966  -2.9683363 ]]
#################
[[ 1.763809    1.6564164   0.2934424 ]
 [-1.9058126   0.78015935  2.3392718 ]
 [-0.5015623  -1.0995766   1.8317    ]]
#################
[[1.4731219  0.14481425 0.06334925]
 [1.649636   1.6003318  0.00699878]
 [0.34299183 0.08751869 0.10181689]]
#################
[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [4 5]
 [2 3]]


In [48]:
X = tf.random_normal(mean=0, stddev=3, shape=[10,10,3])
x_crop = tf.random_crop(X, size=(5,5,3) )

In [49]:
with tf.Session() as sess:
    print("#################")
    print(sess.run(X))
    print("#################")
    print(sess.run(x_crop))

#################
[[[-0.9168529   1.1670493  -1.2821496 ]
  [-1.3210199   0.6811707  -1.5663056 ]
  [-0.579268   -0.08738568 -3.2789884 ]
  [-0.9731968  -0.29125193 -1.6318231 ]
  [-3.3219903  -0.35517937 -1.1438811 ]
  [ 1.6583948  -0.3501359  -1.8629533 ]
  [-1.4442326  -0.2433414  -3.3467684 ]
  [-0.8661102   0.81342655  1.2583712 ]
  [-3.384081   -0.9784894  -3.7061334 ]
  [-0.39958674 -2.379116    4.0434275 ]]

 [[-8.118841    3.112741    1.4926996 ]
  [-1.2165599   0.20423506  1.0512346 ]
  [ 0.9823773  -2.5625272  -3.1881576 ]
  [-2.7005856  -3.2078047   1.6613799 ]
  [-1.3910891   2.7004046  -3.0915952 ]
  [ 0.6296134  -1.1195595  -2.9664898 ]
  [ 1.921257    0.11652425  5.005542  ]
  [-3.339126   -2.878434    2.073212  ]
  [-0.24882337 -0.9046731   0.23058006]
  [ 3.3874521   5.3376284  -2.2169158 ]]

 [[ 2.1689978   1.9352698   2.6692603 ]
  [-0.67217934 -2.8458772  -4.723139  ]
  [ 1.7604938  -2.7924821   2.3750408 ]
  [-2.0756788   1.467663   -2.8174348 ]
  [-0.11678864  0.